spring:
  application:
    name: AtmSystemMaven
  datasource:
    url: jdbc:postgresql://localhost:5432/atm
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: atm
  flyway:
    locations: classpath:db/migration
    enabled: true
    default-schema: ${spring.datasource.hikari.schema}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  shell:
    interactive:
      enabled: true
  security:
    atm:
      hash-algorithm: SHA-256
logging:
  level:
    ru:
      flish1: debug



